spring:
  application:
    name: rotapro-backend
  profiles:
    active: test
  flyway:
    enabled: true
    table: tb_controle_migracoes_frota
    locations: classpath:db/migration

security:
  client-id: ${CLIENT_ID:myclientid}
  client-secret: ${CLIENT_SECRET:myclientsecret}
  jwt:
    duration: ${JWT_DURATION:86400}

cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:4200}