spring:
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: ./target/create.sql # Define o local onde o arquivo será gerado
      hibernate:
        hbm2ddl:
          delimiter: ";" # Define o delimitador para os comandos SQL
    hibernate:
      ddl-auto: create # Garante que o esquema seja recriado a cada inicialização
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

postgresql:
  datasource:
    jdbcUrl: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: ${POSTGRES_DRIVER_CLASS_NAME}

oracle:
  datasource:
    jdbcUrl: ${ORACLE_JDBC_URL}
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
    driver-class-name: ${ORACLE_DRIVER_CLASS_NAME}
